version: "3.3"
services:
  demo_metabase:
    container_name: cq_demo_metabase
    restart: always
    build: ./metabase
    ports:
      - 3000:3000
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - ./.metabase:/metabase-data
  demo_postgres:
    container_name: cq_demo_postgres
    restart: always
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_USER=cq
      - POSTGRES_DB=cq
    volumes:
      - ./.db:/var/lib/postgresql/data:rw
  demo_cq_cron:
    container_name: demo_cq_cron
    restart: always
    build: cloudquery
    volumes:
      - ./daily.yml:/app/daily.yml:ro
    environment:
      - PG_CONNECTION_STRING="postgresql://cq:password123@cq_demo_postgres:5432/cq?sslmode=disable"
    env_file:
      - .env